name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install Node 18
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name : Npm Install
        run: npm install
        
      - name : Lint
        run : npm run lint
        
      - name: Test with coverage
        run: npm run test:coverage
        
      - name : Check Path
        run: ls -la && pwd && ls -la /
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@9598b8a83feef37de07f549027fab50ecffe6a6e
        if: success() || failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.sources=src
            -Dsonar.tests=src/tests
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
             ${{ github.event_name == 'pull_request' && format('-Dsonar.pullrequest.key=%s -Dsonar.pullrequest.branch=%s -Dsonar.pullrequest.base=%s', github.event.pull_request.number, github.head_ref, github.base_ref) || '' }}
            
  # Test_Docker:
  #   runs-on: ubuntu-latest
  #   steps:

  #     #Checkout Repository
  #     - uses: actions/checkout@v3
      
  #     # Docker Build
  #     - uses: docker/build-push-action@v3
  #       with:
  #         push: false
  #         file: ./Dockerfile
  #         tags: front-stage:test
  #         build-args: |
  #           password=${{ secrets.DOCKER_PASS }}
